name: easy_udp
description: >
  This library provides a wrapper over RawDatagramSocket to gracefully handle
  UDP connections in dartlang. 😆
version: 1.2.0
homepage: https://github.com//xtyxtyx/easy_udp
# author: xuty <xty50337@hotmail.com>
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  async: ^2.8.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.0.0
